development:
  adapter: mysql
  database: contents_development
  username: root
  password: password
  host: localhost
  port: 3306
 
test:
  adapter: mysql
  database: contents_development
  username: root
  password: password
  host: localhost
  port: 3306
